- block:
  # - name: Install requisite packages
  #   apt:
  #     pkg:
  #     - python3-pip
  #     - python3-dev
  #     - build-essential
  #     - libssl-dev
  #     - libffi-dev
  #     - python3-setuptools
  #     - python3-venv
  #     - virtualenv
  #   become: true

  # - name: Create app directory
  #   ansible.builtin.file:
  #     path: "{{ cba_api_dir }}"
  #     state: directory

  # - name: Git checkout the flask app
  #   ansible.builtin.git:
  #     repo: https://github.com/vnopenroads/cba-server.git
  #     dest: "{{ cba_api_dir }}"
  #     version: jamiecook/flaskify

  # - name: Install virtualenv via pip
  #   pip:
  #     name: virtualenv
  #     executable: pip3
  #   become: true

  # - name: Install wsgi requirements
  #   pip:
  #     name:
  #       - wheel
  #       - uwsgi
  #       - flask
  #     virtualenv: "{{ cba_api_dir }}/flask_version/venv"
  #     virtualenv_python: /usr/bin/python3

  # - name: Install app requirements
  #   pip:
  #     requirements: "{{ cba_api_dir }}/flask_version/requirements.txt"
  #     virtualenv: "{{ cba_api_dir }}/flask_version/venv"
  #     virtualenv_python: /usr/bin/python3

  # - name: Template out the systemd service for uwsgi
  #   ansible.builtin.template:
  #     src: uwsgi.service
  #     dest: /etc/systemd/system/cba-api.uwsgi.service
  #   become: true

  # - name: Start and enable the service
  #   ansible.builtin.systemd:
  #     name: cba-api.uwsgi
  #     state: started
  #     enabled: yes
  #   become: true

  - name: Template out the nginx vhost config
    ansible.builtin.template:
      src: nginx-cba-api.conf
      dest: /etc/nginx/sites-available/cba-api.conf
    become: true

  - name: Symlink the vhost config from available to enabled
    ansible.builtin.file:
      src: /etc/nginx/sites-available/cba-api.conf
      dest: /etc/nginx/sites-enabled/cba-api.conf
      state: link
    become: true
    notify: restart nginx





  tags: wsgi
