- block:
  # - name: Install requisite packages
  #   apt:
  #     pkg:
  #     - python3-pip
  #     - python3-dev
  #     - build-essential
  #     - libssl-dev
  #     - libffi-dev
  #     - python3-setuptools
  #     - python3-venv
  #     - virtualenv
  #   become: true

  - name: Git checkout the flask app
    ansible.builtin.git:
      repo: https://github.com/vnopenroads/cba-server.git
      dest: "{{ cba_api_dir }}"
      version: jamiecook/flaskify
    notify: 
      - restart nginx

  - name: Git checkout the python lib
    ansible.builtin.git:
      repo: https://github.com/vnopenroads/roads-cba-py.git 
      dest: "{{ cba_py_dir }}"
      version: jamiecook/tidy_up 
    notify: 
      - restart nginx
      - restart wsgi

  # - name: Install virtualenv via pip
  #   pip:
  #     name: virtualenv
  #     executable: pip3
  #   become: true

  - name: Install wsgi requirements
    pip:
      name:
        - wheel
        - uwsgi
        - flask
      virtualenv: "{{ cba_api_dir }}/venv"
      virtualenv_python: /usr/bin/python3

  - name: Install app requirements
    pip:
      requirements: "{{ cba_api_dir }}/requirements.txt"
      virtualenv: "{{ cba_api_dir }}/venv"
      virtualenv_python: /usr/bin/python3
      chdir: "{{ cba_api_dir }}"

  - name: Template out the systemd service for uwsgi
    ansible.builtin.template:
      src: uwsgi.service
      dest: /etc/systemd/system/cba-api.uwsgi.service
    become: true
    notify: 
      - restart wsgi
      - restart nginx

  - name: Template out the wsgi ini file
    ansible.builtin.template:
      src: uwsgi.ini
      dest: "{{ cba_api_dir }}/cba-api.ini"
    become: true
    notify: 
      - restart wsgi


  - name: "foo"
    command: cat /etc/systemd/system/cba-api.uwsgi.service
    register: hello

  - debug: msg="{{ hello.stdout_lines }}"

  - name: Start and enable the service
    ansible.builtin.systemd:
      name: cba-api.uwsgi
      state: started
      enabled: yes
      daemon_reload: yes
    become: true

  - name: Template out the nginx vhost config
    ansible.builtin.template:
      src: nginx-cba-api.conf
      dest: /etc/nginx/sites-available/cba-api.conf
    become: true
    notify: restart nginx

  # - name: Symlink the vhost config from available to enabled
  #   ansible.builtin.file:
  #     src: /etc/nginx/sites-available/cba-api.conf
  #     dest: /etc/nginx/sites-enabled/cba-api.conf
  #     state: link
  #   become: true
  #   notify: restart nginx

  tags: cba-api 
