- block:

  # - name: Create log directory
  #   ansible.builtin.file:
  #     path: "/home/ubuntu/log"
  #     state: directory

  # - name: Setup APT Sources for Node/Yarn
  #   shell: "{{ item }}"
  #   with_items: 
  #   - "curl -sL https://deb.nodesource.com/setup_14.x | bash -"
  #   - "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -"
  #   - "echo 'deb https://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list"
  #   become: true

  # - name: install Node/Yarn
  #   apt: 
  #     update_cache: true
  #     pkg: 
  #       - nodejs
  #       - yarn
  #       - make
  #       - gcc
  #       - g++
  #   become: true

  # - name: Create app directory
  #   ansible.builtin.file:
  #     path: "{{ node_app_dir }}"
  #     state: directory

  - name: Git checkout the python lib
    ansible.builtin.git:
      repo: https://github.com/vnopenroads/openroads-vn-api.git 
      dest: "{{ node_app_dir }}/"
      version: jamiecook/docker-image
    notify: 
      - restart API
  
  - name: Yarn Install
    command: 
      cmd: yarn install
      chdir: "{{ node_app_dir }}"
    notify: restart API

  tags: node-app
